// Code generated by mockery v2.43.2. DO NOT EDIT.

package ocpp16_test

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// MockChargePointConnection is an autogenerated mock type for the ChargePointConnection type
type MockChargePointConnection struct {
	mock.Mock
}

type MockChargePointConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargePointConnection) EXPECT() *MockChargePointConnection_Expecter {
	return &MockChargePointConnection_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with given fields:
func (_m *MockChargePointConnection) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChargePointConnection_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockChargePointConnection_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockChargePointConnection_Expecter) ID() *MockChargePointConnection_ID_Call {
	return &MockChargePointConnection_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockChargePointConnection_ID_Call) Run(run func()) *MockChargePointConnection_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChargePointConnection_ID_Call) Return(_a0 string) *MockChargePointConnection_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargePointConnection_ID_Call) RunAndReturn(run func() string) *MockChargePointConnection_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function with given fields:
func (_m *MockChargePointConnection) RemoteAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// MockChargePointConnection_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type MockChargePointConnection_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *MockChargePointConnection_Expecter) RemoteAddr() *MockChargePointConnection_RemoteAddr_Call {
	return &MockChargePointConnection_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *MockChargePointConnection_RemoteAddr_Call) Run(run func()) *MockChargePointConnection_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChargePointConnection_RemoteAddr_Call) Return(_a0 net.Addr) *MockChargePointConnection_RemoteAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargePointConnection_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *MockChargePointConnection_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// TLSConnectionState provides a mock function with given fields:
func (_m *MockChargePointConnection) TLSConnectionState() *tls.ConnectionState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TLSConnectionState")
	}

	var r0 *tls.ConnectionState
	if rf, ok := ret.Get(0).(func() *tls.ConnectionState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.ConnectionState)
		}
	}

	return r0
}

// MockChargePointConnection_TLSConnectionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSConnectionState'
type MockChargePointConnection_TLSConnectionState_Call struct {
	*mock.Call
}

// TLSConnectionState is a helper method to define mock.On call
func (_e *MockChargePointConnection_Expecter) TLSConnectionState() *MockChargePointConnection_TLSConnectionState_Call {
	return &MockChargePointConnection_TLSConnectionState_Call{Call: _e.mock.On("TLSConnectionState")}
}

func (_c *MockChargePointConnection_TLSConnectionState_Call) Run(run func()) *MockChargePointConnection_TLSConnectionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChargePointConnection_TLSConnectionState_Call) Return(_a0 *tls.ConnectionState) *MockChargePointConnection_TLSConnectionState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChargePointConnection_TLSConnectionState_Call) RunAndReturn(run func() *tls.ConnectionState) *MockChargePointConnection_TLSConnectionState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChargePointConnection creates a new instance of MockChargePointConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargePointConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargePointConnection {
	mock := &MockChargePointConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
